// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
insert into users(
name, type
) values (
$1, $2
)
returning id, name, type, role
`

type CreateAuthorParams struct {
	Name string
	Type AccountType
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (User, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Type)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Role,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getUser = `-- name: GetUser :one
select id, name, type, role from users
where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, name, type, role from users
order by name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users
  set name = $2
WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}

const updateUserType = `-- name: UpdateUserType :exec
UPDATE users
  set type = $2
WHERE id = $1
`

type UpdateUserTypeParams struct {
	ID   pgtype.UUID
	Type AccountType
}

func (q *Queries) UpdateUserType(ctx context.Context, arg UpdateUserTypeParams) error {
	_, err := q.db.Exec(ctx, updateUserType, arg.ID, arg.Type)
	return err
}
