// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuestUser = `-- name: CreateGuestUser :one
insert into users(
  name, type
) values (
  $1, 'guest'
)
returning id, name, email, password_hash, type, role, created_at
`

func (q *Queries) CreateGuestUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, createGuestUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Type,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createRegisteredUser = `-- name: CreateRegisteredUser :one
insert into users(
  name, email, password_hash, type
) values (
  $1, $2, $3, 'registered'
)
returning id, name, email, password_hash, type, role, created_at
`

type CreateRegisteredUserParams struct {
	Name         string
	Email        pgtype.Text
	PasswordHash pgtype.Text
}

func (q *Queries) CreateRegisteredUser(ctx context.Context, arg CreateRegisteredUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createRegisteredUser, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Type,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
select id, name, email, password_hash, type, role, created_at from users
where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Type,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, name, email, password_hash, type, role, created_at from users
where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Type,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, name, email, password_hash, type, role, created_at from users
order by name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Type,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users
  set name = $2
WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
  set role = $2
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID
	Role UserRole
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserType = `-- name: UpdateUserType :exec
UPDATE users
  set type = $2
WHERE id = $1
`

type UpdateUserTypeParams struct {
	ID   pgtype.UUID
	Type AccountType
}

func (q *Queries) UpdateUserType(ctx context.Context, arg UpdateUserTypeParams) error {
	_, err := q.db.Exec(ctx, updateUserType, arg.ID, arg.Type)
	return err
}

const upgradeGuestToRegistered = `-- name: UpgradeGuestToRegistered :one
UPDATE users
  SET email = $2,
      password_hash = $3,
      type = 'registered'
WHERE id = $1 AND type = 'guest'
RETURNING id, name, email, password_hash, type, role, created_at
`

type UpgradeGuestToRegisteredParams struct {
	ID           pgtype.UUID
	Email        pgtype.Text
	PasswordHash pgtype.Text
}

func (q *Queries) UpgradeGuestToRegistered(ctx context.Context, arg UpgradeGuestToRegisteredParams) (User, error) {
	row := q.db.QueryRow(ctx, upgradeGuestToRegistered, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Type,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
